#########################################################################
#Made by Adventquest													#
#Xp attribution for a give player										#
#########################################################################
#summon minecraft:experience_orb ~ ~1 ~ {Value:77777,Motion:[0.0,0.75,0.0]}
execute if score totalultima SPELL31 matches 1 run summon minecraft:shulker ~ ~ ~ {Tags:["runebonus_ultima"],NoAI:1,Silent:1,PersistenceRequired:1,Attributes:[{Name:generic.attack_damage,Base:0.0},{Name:generic.max_health,Base:7.7}],Health:7.7,active_effects:[{id:invisibility,amplifier:1,duration:2147483647,ambient:1,show_particles:0},{id:wither,amplifier:1,duration:2147483647,ambient:1,show_particles:0},{id:glowing,amplifier:0,duration:480,ambient:1,show_particles:0}],DeathLootTable:"att2:rune_bonus/runes_ultima_rewards_1"}
execute if score totalultima SPELL31 matches 2 run summon minecraft:shulker ~ ~ ~ {Tags:["runebonus_ultima"],NoAI:1,Silent:1,PersistenceRequired:1,Attributes:[{Name:generic.attack_damage,Base:0.0},{Name:generic.max_health,Base:7.7}],Health:7.7,active_effects:[{id:invisibility,amplifier:1,duration:2147483647,ambient:1,show_particles:0},{id:wither,amplifier:1,duration:2147483647,ambient:1,show_particles:0},{id:glowing,amplifier:0,duration:480,ambient:1,show_particles:0}],DeathLootTable:"att2:rune_bonus/runes_ultima_rewards_2"}
execute if score totalultima SPELL31 matches 3 run summon minecraft:shulker ~ ~ ~ {Tags:["runebonus_ultima"],NoAI:1,Silent:1,PersistenceRequired:1,Attributes:[{Name:generic.attack_damage,Base:0.0},{Name:generic.max_health,Base:7.7}],Health:7.7,active_effects:[{id:invisibility,amplifier:1,duration:2147483647,ambient:1,show_particles:0},{id:wither,amplifier:1,duration:2147483647,ambient:1,show_particles:0},{id:glowing,amplifier:0,duration:480,ambient:1,show_particles:0}],DeathLootTable:"att2:rune_bonus/runes_ultima_rewards_3"}
execute if score totalultima SPELL31 matches 4 run summon minecraft:shulker ~ ~ ~ {Tags:["runebonus_ultima"],NoAI:1,Silent:1,PersistenceRequired:1,Attributes:[{Name:generic.attack_damage,Base:0.0},{Name:generic.max_health,Base:7.7}],Health:7.7,active_effects:[{id:invisibility,amplifier:1,duration:2147483647,ambient:1,show_particles:0},{id:wither,amplifier:1,duration:2147483647,ambient:1,show_particles:0},{id:glowing,amplifier:0,duration:480,ambient:1,show_particles:0}],DeathLootTable:"att2:rune_bonus/runes_ultima_rewards_4"}
execute if score totalultima SPELL31 matches 5 run summon minecraft:shulker ~ ~ ~ {Tags:["runebonus_ultima"],NoAI:1,Silent:1,PersistenceRequired:1,Attributes:[{Name:generic.attack_damage,Base:0.0},{Name:generic.max_health,Base:7.7}],Health:7.7,active_effects:[{id:invisibility,amplifier:1,duration:2147483647,ambient:1,show_particles:0},{id:wither,amplifier:1,duration:2147483647,ambient:1,show_particles:0},{id:glowing,amplifier:0,duration:480,ambient:1,show_particles:0}],DeathLootTable:"att2:rune_bonus/runes_ultima_rewards_5"}
execute if score totalultima SPELL31 matches 6 run summon minecraft:shulker ~ ~ ~ {Tags:["runebonus_ultima"],NoAI:1,Silent:1,PersistenceRequired:1,Attributes:[{Name:generic.attack_damage,Base:0.0},{Name:generic.max_health,Base:7.7}],Health:7.7,active_effects:[{id:invisibility,amplifier:1,duration:2147483647,ambient:1,show_particles:0},{id:wither,amplifier:1,duration:2147483647,ambient:1,show_particles:0},{id:glowing,amplifier:0,duration:480,ambient:1,show_particles:0}],DeathLootTable:"att2:rune_bonus/runes_ultima_rewards_6"}
execute if score totalultima SPELL31 matches 7 run summon minecraft:shulker ~ ~ ~ {Tags:["runebonus_ultima"],NoAI:1,Silent:1,PersistenceRequired:1,Attributes:[{Name:generic.attack_damage,Base:0.0},{Name:generic.max_health,Base:7.7}],Health:7.7,active_effects:[{id:invisibility,amplifier:1,duration:2147483647,ambient:1,show_particles:0},{id:wither,amplifier:1,duration:2147483647,ambient:1,show_particles:0},{id:glowing,amplifier:0,duration:480,ambient:1,show_particles:0}],DeathLootTable:"att2:rune_bonus/runes_ultima_rewards_7"}
execute if score totalultima SPELL31 matches 8 run summon minecraft:shulker ~ ~ ~ {Tags:["runebonus_ultima"],NoAI:1,Silent:1,PersistenceRequired:1,Attributes:[{Name:generic.attack_damage,Base:0.0},{Name:generic.max_health,Base:7.7}],Health:7.7,active_effects:[{id:invisibility,amplifier:1,duration:2147483647,ambient:1,show_particles:0},{id:wither,amplifier:1,duration:2147483647,ambient:1,show_particles:0},{id:glowing,amplifier:0,duration:480,ambient:1,show_particles:0}],DeathLootTable:"att2:rune_bonus/runes_ultima_rewards_8"}
execute if score totalultima SPELL31 matches 9 run summon minecraft:shulker ~ ~ ~ {Tags:["runebonus_ultima"],NoAI:1,Silent:1,PersistenceRequired:1,Attributes:[{Name:generic.attack_damage,Base:0.0},{Name:generic.max_health,Base:7.7}],Health:7.7,active_effects:[{id:invisibility,amplifier:1,duration:2147483647,ambient:1,show_particles:0},{id:wither,amplifier:1,duration:2147483647,ambient:1,show_particles:0},{id:glowing,amplifier:0,duration:480,ambient:1,show_particles:0}],DeathLootTable:"att2:rune_bonus/runes_ultima_rewards_9"}
execute if score totalultima SPELL31 matches 10.. run summon minecraft:shulker ~ ~ ~ {Tags:["runebonus_ultima"],NoAI:1,Silent:1,PersistenceRequired:1,Attributes:[{Name:generic.attack_damage,Base:0.0},{Name:generic.max_health,Base:7.7}],Health:7.7,active_effects:[{id:invisibility,amplifier:1,duration:2147483647,ambient:1,show_particles:0},{id:wither,amplifier:1,duration:2147483647,ambient:1,show_particles:0},{id:glowing,amplifier:0,duration:480,ambient:1,show_particles:0}],DeathLootTable:"att2:rune_bonus/runes_ultima_rewards_10"}

execute if score totalultima SPELL31 matches 2188..6560 run summon minecraft:experience_orb ~ ~1 ~ {Value:77777,Motion:[0.0,0.75,0.0]}
execute if score totalultima SPELL31 matches 2187.. run summon minecraft:experience_orb ~ ~1 ~ {Value:62216,Motion:[0.0,0.5,0.0]}
execute if score totalultima SPELL31 matches 729.. run summon minecraft:experience_orb ~ ~1 ~ {Value:54439,Motion:[0.25,0.5,-0.25]}
execute if score totalultima SPELL31 matches 243.. run summon minecraft:experience_orb ~ ~1 ~ {Value:46662,Motion:[0.0,0.5,0.0]}
execute if score totalultima SPELL31 matches 81.. run summon minecraft:experience_orb ~ ~1 ~ {Value:38885,Motion:[-0.25,0.5,0.25]}
execute if score totalultima SPELL31 matches 27.. run summon minecraft:experience_orb ~ ~1 ~ {Value:31108,Motion:[0.0,0.5,0.0]}
execute if score totalultima SPELL31 matches 9.. run summon minecraft:experience_orb ~ ~1 ~ {Value:23331,Motion:[-0.25,0.5,-0.25]}
execute if score totalultima SPELL31 matches 3.. run summon minecraft:experience_orb ~ ~1 ~ {Value:15554,Motion:[0.0,0.5,0.0]}
execute if score totalultima SPELL31 matches 1.. run summon minecraft:experience_orb ~ ~1 ~ {Value:7777,Motion:[0.0,0.5,0.0]}