#########################################################################
#Made by Adventquest													#
#Xp attribution for a give player	@s SPELL_SLCT matches 331									#
#########################################################################

execute if score totallow SPELL31 matches 1 run summon minecraft:shulker ~ ~ ~ {Tags:["runebonus_low"],NoAI:1,Silent:1,PersistenceRequired:1,Attributes:[{Name:generic.attack_damage,Base:0.0},{Name:generic.max_health,Base:7.7}],Health:7.7,active_effects:[{id:invisibility,amplifier:1,duration:2147483647,ambient:1,show_particles:0},{id:wither,amplifier:1,duration:2147483647,ambient:1,show_particles:0},{id:glowing,amplifier:0,duration:480,ambient:1,show_particles:0}],DeathLootTable:"att2:rune_bonus/runes_c_rewards_1"}
execute if score totallow SPELL31 matches 2..3 run summon minecraft:shulker ~ ~ ~ {Tags:["runebonus_low"],NoAI:1,Silent:1,PersistenceRequired:1,Attributes:[{Name:generic.attack_damage,Base:0.0},{Name:generic.max_health,Base:7.7}],Health:7.7,active_effects:[{id:invisibility,amplifier:1,duration:2147483647,ambient:1,show_particles:0},{id:wither,amplifier:1,duration:2147483647,ambient:1,show_particles:0},{id:glowing,amplifier:0,duration:480,ambient:1,show_particles:0}],DeathLootTable:"att2:rune_bonus/runes_c_rewards_2"}
execute if score totallow SPELL31 matches 4..9 run summon minecraft:shulker ~ ~ ~ {Tags:["runebonus_low"],NoAI:1,Silent:1,PersistenceRequired:1,Attributes:[{Name:generic.attack_damage,Base:0.0},{Name:generic.max_health,Base:7.7}],Health:7.7,active_effects:[{id:invisibility,amplifier:1,duration:2147483647,ambient:1,show_particles:0},{id:wither,amplifier:1,duration:2147483647,ambient:1,show_particles:0},{id:glowing,amplifier:0,duration:480,ambient:1,show_particles:0}],DeathLootTable:"att2:rune_bonus/runes_c_rewards_3"}
execute if score totallow SPELL31 matches 10..27 run summon minecraft:shulker ~ ~ ~ {Tags:["runebonus_low"],NoAI:1,Silent:1,PersistenceRequired:1,Attributes:[{Name:generic.attack_damage,Base:0.0},{Name:generic.max_health,Base:7.7}],Health:7.7,active_effects:[{id:invisibility,amplifier:1,duration:2147483647,ambient:1,show_particles:0},{id:wither,amplifier:1,duration:2147483647,ambient:1,show_particles:0},{id:glowing,amplifier:0,duration:480,ambient:1,show_particles:0}],DeathLootTable:"att2:rune_bonus/runes_c_rewards_4"}
execute if score totallow SPELL31 matches 28..81 run summon minecraft:shulker ~ ~ ~ {Tags:["runebonus_low"],NoAI:1,Silent:1,PersistenceRequired:1,Attributes:[{Name:generic.attack_damage,Base:0.0},{Name:generic.max_health,Base:7.7}],Health:7.7,active_effects:[{id:invisibility,amplifier:1,duration:2147483647,ambient:1,show_particles:0},{id:wither,amplifier:1,duration:2147483647,ambient:1,show_particles:0},{id:glowing,amplifier:0,duration:480,ambient:1,show_particles:0}],DeathLootTable:"att2:rune_bonus/runes_c_rewards_5"}
execute if score totallow SPELL31 matches 82..243 run summon minecraft:shulker ~ ~ ~ {Tags:["runebonus_low"],NoAI:1,Silent:1,PersistenceRequired:1,Attributes:[{Name:generic.attack_damage,Base:0.0},{Name:generic.max_health,Base:7.7}],Health:7.7,active_effects:[{id:invisibility,amplifier:1,duration:2147483647,ambient:1,show_particles:0},{id:wither,amplifier:1,duration:2147483647,ambient:1,show_particles:0},{id:glowing,amplifier:0,duration:480,ambient:1,show_particles:0}],DeathLootTable:"att2:rune_bonus/runes_c_rewards_6"}
execute if score totallow SPELL31 matches 244..729 run summon minecraft:shulker ~ ~ ~ {Tags:["runebonus_low"],NoAI:1,Silent:1,PersistenceRequired:1,Attributes:[{Name:generic.attack_damage,Base:0.0},{Name:generic.max_health,Base:7.7}],Health:7.7,active_effects:[{id:invisibility,amplifier:1,duration:2147483647,ambient:1,show_particles:0},{id:wither,amplifier:1,duration:2147483647,ambient:1,show_particles:0},{id:glowing,amplifier:0,duration:480,ambient:1,show_particles:0}],DeathLootTable:"att2:rune_bonus/runes_c_rewards_7"}
execute if score totallow SPELL31 matches 730..2187 run summon minecraft:shulker ~ ~ ~ {Tags:["runebonus_low"],NoAI:1,Silent:1,PersistenceRequired:1,Attributes:[{Name:generic.attack_damage,Base:0.0},{Name:generic.max_health,Base:7.7}],Health:7.7,active_effects:[{id:invisibility,amplifier:1,duration:2147483647,ambient:1,show_particles:0},{id:wither,amplifier:1,duration:2147483647,ambient:1,show_particles:0},{id:glowing,amplifier:0,duration:480,ambient:1,show_particles:0}],DeathLootTable:"att2:rune_bonus/runes_c_rewards_8"}
execute if score totallow SPELL31 matches 2188..6560 run summon minecraft:shulker ~ ~ ~ {Tags:["runebonus_low"],NoAI:1,Silent:1,PersistenceRequired:1,Attributes:[{Name:generic.attack_damage,Base:0.0},{Name:generic.max_health,Base:7.7}],Health:7.7,active_effects:[{id:invisibility,amplifier:1,duration:2147483647,ambient:1,show_particles:0},{id:wither,amplifier:1,duration:2147483647,ambient:1,show_particles:0},{id:glowing,amplifier:0,duration:480,ambient:1,show_particles:0}],DeathLootTable:"att2:rune_bonus/runes_c_rewards_9"}

execute if score totallow SPELL31 matches 2188..6560 run summon minecraft:experience_orb ~ ~1 ~ {Value:77,Motion:[0.0,0.75,0.0]}
execute if score totallow SPELL31 matches 2187.. run summon minecraft:experience_orb ~ ~1 ~ {Value:56,Motion:[0.0,0.5,0.0]}
execute if score totallow SPELL31 matches 729.. run summon minecraft:experience_orb ~ ~1 ~ {Value:49,Motion:[0.25,0.5,-0.25]}
execute if score totallow SPELL31 matches 243.. run summon minecraft:experience_orb ~ ~1 ~ {Value:42,Motion:[0.0,0.5,0.0]}
execute if score totallow SPELL31 matches 81.. run summon minecraft:experience_orb ~ ~1 ~ {Value:35,Motion:[-0.25,0.5,0.25]}
execute if score totallow SPELL31 matches 27.. run summon minecraft:experience_orb ~ ~1 ~ {Value:28,Motion:[0.0,0.5,0.0]}
execute if score totallow SPELL31 matches 9.. run summon minecraft:experience_orb ~ ~1 ~ {Value:21,Motion:[-0.25,0.5,-0.25]}
execute if score totallow SPELL31 matches 3.. run summon minecraft:experience_orb ~ ~1 ~ {Value:14,Motion:[0.0,0.5,0.0]}
execute if score totallow SPELL31 matches 1.. run summon minecraft:experience_orb ~ ~1 ~ {Value:7,Motion:[0.0,0.5,0.0]}
